title: DeepIdea Lab
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/main" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mtagab007
# Build settings
theme: minima
plugins:
  - jekyll-feed